Components:
- component_name: "Any camera on video_device"
  component_type: "2d_camera"
  package_name: "example_temoto_config_pkg"
  executable:  "usb_cam_remappable.launch"
  output_topics:
    camera_data: "usb_cam/image_raw"
    camera_data_compressed: "usb_cam/image_raw/compressed"
    camera_info: "usb_cam/camera_info"
  required_parameters:
    frame_id: "camera_link"
    video_device: "/dev/video0"

- component_name: "String spammer 0"
  component_type: "cs_test_0"
  package_name: "example_temoto_config_pkg"
  executable:  "component_string_0"
  output_topics:
    data_type_0: "cs_0_pub_0"
    data_type_1: "cs_0_pub_1"

- component_name: "String spammer 1"
  component_type: "cs_test_1"
  package_name: "example_temoto_config_pkg"
  executable:  "component_string_1"
  input_topics:
    data_type_0: "cs_1_sub_0"
    data_type_1: "cs_1_sub_1"
  output_topics:
    data_type_2: "cs_1_pub_0"
    data_type_3: "cs_1_pub_1"

- component_name: "String spammer 2"
  component_type: "cs_test_2"
  package_name: "example_temoto_config_pkg"
  executable:  "component_string_2"
  input_topics:
    data_type_2: "cs_2_sub_0"
    data_type_3: "cs_2_sub_1"
  output_topics:
    data_type_4: "cs_2_pub_0"
    data_type_5: "cs_2_pub_1"
