---
testpipe:
- method:
  - segment_type: "cs_test_0"
    output_topic_types:
      - data_type_0
      - data_type_1

  - segment_type: "cs_test_1"
    input_topic_types:
      - data_type_0
      - data_type_1
    output_topic_types:
      - data_type_2
      - data_type_3

  - segment_type: "cs_test_2"
    input_topic_types:
      - data_type_2
      - data_type_3
    output_topic_types:
      - data_type_4
      - data_type_5
