Robots:
- robot_name: "jackal_sim"
  description: "Clearpath Jackal mobile skid-steer platform - Simulated"
  reliability: 0.8
  urdf:
    package_name: "jackal_description"
    executable: "urdf/jackal.urdf.xacro"
  navigation:
    controller:
      package_name: "jackal_navigation"
      executable: "amcl_demo.launch"
      global_planner: "navfn/NavfnROS"
      local_planner: "base_local_planner/TrajectoryPlannerROS"
      scan_topic: "remapped_scan"
      pose_topic: "amcl_pose"
      args: "scan_topic:=remapped_scan"
    driver:
      package_name: "jackal_gazebo" 
      executable: "jackal_world.launch"
      args: "joystick:=false config:=front_laser"
      odom_topic: "odometry/filtered"
      cmd_vel_topic: "cmd_vel"